/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_brach_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {15, 1, 1};
static const casadi_int casadi_s2[3] = {12, 1, 1};
static const casadi_int casadi_s3[3] = {19, 1, 1};
static const casadi_int casadi_s4[3] = {19, 4, 1};
static const casadi_int casadi_s5[3] = {19, 12, 1};
static const casadi_int casadi_s6[3] = {19, 19, 1};

/* brach_eval_f_dyn:(i0[4],i1[15])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_f_dyn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int brach_eval_f_dyn_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_f_dyn_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_f_dyn_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int brach_eval_f_dyn_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_f_dyn_release(int mem) {
}

CASADI_SYMBOL_EXPORT void brach_eval_f_dyn_incref(void) {
}

CASADI_SYMBOL_EXPORT void brach_eval_f_dyn_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_f_dyn_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_f_dyn_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real brach_eval_f_dyn_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_f_dyn_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_f_dyn_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_f_dyn_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_f_dyn_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int brach_eval_f_dyn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_f_dyn_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* brach_eval_g_eq:(i0[4],i1[15])->(o0[12]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25;
  a00=arg[0]? arg[0][3] : 0;
  a01=20.;
  a01=(a00/a01);
  a02=arg[1]? arg[1][2] : 0;
  a03=arg[1]? arg[1][12] : 0;
  a04=cos(a03);
  a04=(a02*a04);
  a04=(a01*a04);
  a05=-4.1393876913398131e+00;
  a06=arg[0]? arg[0][0] : 0;
  a07=(a05*a06);
  a08=3.2247448713915867e+00;
  a09=arg[1]? arg[1][0] : 0;
  a10=(a08*a09);
  a07=(a07+a10);
  a10=1.1678400846904051e+00;
  a11=arg[1]? arg[1][4] : 0;
  a12=(a10*a11);
  a07=(a07+a12);
  a12=-2.5319726474218096e-01;
  a13=arg[1]? arg[1][8] : 0;
  a14=(a12*a13);
  a07=(a07+a14);
  a04=(a04-a07);
  if (res[0]!=0) res[0][0]=a04;
  a04=sin(a03);
  a04=(a02*a04);
  a04=(a01*a04);
  a07=arg[0]? arg[0][1] : 0;
  a14=(a05*a07);
  a15=arg[1]? arg[1][1] : 0;
  a16=(a08*a15);
  a14=(a14+a16);
  a16=arg[1]? arg[1][5] : 0;
  a17=(a10*a16);
  a14=(a14+a17);
  a17=arg[1]? arg[1][9] : 0;
  a18=(a12*a17);
  a14=(a14+a18);
  a04=(a04-a14);
  if (res[0]!=0) res[0][1]=a04;
  a04=9.8100000000000005e+00;
  a03=sin(a03);
  a03=(a04*a03);
  a03=(a01*a03);
  a14=arg[0]? arg[0][2] : 0;
  a18=(a05*a14);
  a19=(a08*a02);
  a18=(a18+a19);
  a19=arg[1]? arg[1][6] : 0;
  a20=(a10*a19);
  a18=(a18+a20);
  a20=arg[1]? arg[1][10] : 0;
  a21=(a12*a20);
  a18=(a18+a21);
  a03=(a03-a18);
  if (res[0]!=0) res[0][2]=a03;
  a05=(a05*a00);
  a03=arg[1]? arg[1][3] : 0;
  a08=(a08*a03);
  a05=(a05+a08);
  a08=arg[1]? arg[1][7] : 0;
  a10=(a10*a08);
  a05=(a05+a10);
  a10=arg[1]? arg[1][11] : 0;
  a12=(a12*a10);
  a05=(a05+a12);
  a05=(-a05);
  if (res[0]!=0) res[0][3]=a05;
  a05=arg[1]? arg[1][13] : 0;
  a12=cos(a05);
  a12=(a19*a12);
  a12=(a01*a12);
  a18=1.7393876913398110e+00;
  a21=(a18*a06);
  a22=-3.5678400846904044e+00;
  a23=(a22*a09);
  a21=(a21+a23);
  a23=7.7525512860840906e-01;
  a24=(a23*a11);
  a21=(a21+a24);
  a24=1.0531972647421810e+00;
  a25=(a24*a13);
  a21=(a21+a25);
  a12=(a12-a21);
  if (res[0]!=0) res[0][4]=a12;
  a12=sin(a05);
  a12=(a19*a12);
  a12=(a01*a12);
  a21=(a18*a07);
  a25=(a22*a15);
  a21=(a21+a25);
  a25=(a23*a16);
  a21=(a21+a25);
  a25=(a24*a17);
  a21=(a21+a25);
  a12=(a12-a21);
  if (res[0]!=0) res[0][5]=a12;
  a05=sin(a05);
  a05=(a04*a05);
  a05=(a01*a05);
  a12=(a18*a14);
  a21=(a22*a02);
  a12=(a12+a21);
  a21=(a23*a19);
  a12=(a12+a21);
  a21=(a24*a20);
  a12=(a12+a21);
  a05=(a05-a12);
  if (res[0]!=0) res[0][6]=a05;
  a18=(a18*a00);
  a22=(a22*a03);
  a18=(a18+a22);
  a23=(a23*a08);
  a18=(a18+a23);
  a24=(a24*a10);
  a18=(a18+a24);
  a18=(-a18);
  if (res[0]!=0) res[0][7]=a18;
  a18=arg[1]? arg[1][14] : 0;
  a24=cos(a18);
  a24=(a20*a24);
  a24=(a01*a24);
  a23=-3.0000000000000018e+00;
  a06=(a23*a06);
  a22=5.5319726474218047e+00;
  a09=(a22*a09);
  a06=(a06+a09);
  a09=-7.5319726474218074e+00;
  a11=(a09*a11);
  a06=(a06+a11);
  a11=5.;
  a13=(a11*a13);
  a06=(a06+a13);
  a24=(a24-a06);
  if (res[0]!=0) res[0][8]=a24;
  a24=sin(a18);
  a24=(a20*a24);
  a24=(a01*a24);
  a07=(a23*a07);
  a15=(a22*a15);
  a07=(a07+a15);
  a16=(a09*a16);
  a07=(a07+a16);
  a17=(a11*a17);
  a07=(a07+a17);
  a24=(a24-a07);
  if (res[0]!=0) res[0][9]=a24;
  a18=sin(a18);
  a04=(a04*a18);
  a01=(a01*a04);
  a14=(a23*a14);
  a02=(a22*a02);
  a14=(a14+a02);
  a19=(a09*a19);
  a14=(a14+a19);
  a20=(a11*a20);
  a14=(a14+a20);
  a01=(a01-a14);
  if (res[0]!=0) res[0][10]=a01;
  a23=(a23*a00);
  a22=(a22*a03);
  a23=(a23+a22);
  a09=(a09*a08);
  a23=(a23+a09);
  a11=(a11*a10);
  a23=(a23+a11);
  a23=(-a23);
  if (res[0]!=0) res[0][11]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_g_eq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int brach_eval_g_eq_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_g_eq_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_g_eq_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int brach_eval_g_eq_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_g_eq_release(int mem) {
}

CASADI_SYMBOL_EXPORT void brach_eval_g_eq_incref(void) {
}

CASADI_SYMBOL_EXPORT void brach_eval_g_eq_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_g_eq_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_g_eq_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real brach_eval_g_eq_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_g_eq_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_g_eq_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_g_eq_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_g_eq_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int brach_eval_g_eq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_g_eq_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* brach_eval_g_ineq:(i0[4],i1[15])->(o0[19]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][17]=a0;
  a0=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][18]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_g_ineq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int brach_eval_g_ineq_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_g_ineq_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_g_ineq_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int brach_eval_g_ineq_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_g_ineq_release(int mem) {
}

CASADI_SYMBOL_EXPORT void brach_eval_g_ineq_incref(void) {
}

CASADI_SYMBOL_EXPORT void brach_eval_g_ineq_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_g_ineq_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_g_ineq_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real brach_eval_g_ineq_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_g_ineq_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_g_ineq_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_g_ineq_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_g_ineq_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int brach_eval_g_ineq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_g_ineq_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* brach_eval_J_BAbt:(i0[4],i1[15])->(o0[19x4]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  a1=1.;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a1;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a1;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a0;
  if (res[0]!=0) res[0][55]=a0;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  if (res[0]!=0) res[0][58]=a0;
  if (res[0]!=0) res[0][59]=a0;
  if (res[0]!=0) res[0][60]=a0;
  if (res[0]!=0) res[0][61]=a0;
  if (res[0]!=0) res[0][62]=a0;
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a0;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a0;
  if (res[0]!=0) res[0][67]=a0;
  if (res[0]!=0) res[0][68]=a1;
  if (res[0]!=0) res[0][69]=a0;
  if (res[0]!=0) res[0][70]=a0;
  if (res[0]!=0) res[0][71]=a0;
  if (res[0]!=0) res[0][72]=a0;
  if (res[0]!=0) res[0][73]=a0;
  if (res[0]!=0) res[0][74]=a0;
  if (res[0]!=0) res[0][75]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_BAbt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int brach_eval_J_BAbt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_BAbt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_J_BAbt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int brach_eval_J_BAbt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_J_BAbt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void brach_eval_J_BAbt_incref(void) {
}

CASADI_SYMBOL_EXPORT void brach_eval_J_BAbt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_J_BAbt_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_J_BAbt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real brach_eval_J_BAbt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_J_BAbt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_J_BAbt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_J_BAbt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_J_BAbt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int brach_eval_J_BAbt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_BAbt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* brach_eval_J_Ggt:(i0[4],i1[15])->(o0[19x12]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  a00=-3.2247448713915867e+00;
  if (res[0]!=0) res[0][0]=a00;
  a01=0.;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][3] : 0;
  a03=20.;
  a02=(a02/a03);
  a03=arg[1]? arg[1][12] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  if (res[0]!=0) res[0][2]=a05;
  if (res[0]!=0) res[0][3]=a01;
  a05=-1.1678400846904051e+00;
  if (res[0]!=0) res[0][4]=a05;
  if (res[0]!=0) res[0][5]=a01;
  if (res[0]!=0) res[0][6]=a01;
  if (res[0]!=0) res[0][7]=a01;
  a06=2.5319726474218096e-01;
  if (res[0]!=0) res[0][8]=a06;
  if (res[0]!=0) res[0][9]=a01;
  if (res[0]!=0) res[0][10]=a01;
  if (res[0]!=0) res[0][11]=a01;
  a07=arg[1]? arg[1][2] : 0;
  a08=sin(a03);
  a08=(a07*a08);
  a08=(a02*a08);
  a08=(-a08);
  if (res[0]!=0) res[0][12]=a08;
  if (res[0]!=0) res[0][13]=a01;
  if (res[0]!=0) res[0][14]=a01;
  a08=4.1393876913398131e+00;
  if (res[0]!=0) res[0][15]=a08;
  if (res[0]!=0) res[0][16]=a01;
  if (res[0]!=0) res[0][17]=a01;
  a09=5.0000000000000003e-02;
  a04=(a07*a04);
  a04=(a09*a04);
  if (res[0]!=0) res[0][18]=a04;
  if (res[0]!=0) res[0][19]=a01;
  if (res[0]!=0) res[0][20]=a00;
  a04=sin(a03);
  a10=(a02*a04);
  if (res[0]!=0) res[0][21]=a10;
  if (res[0]!=0) res[0][22]=a01;
  if (res[0]!=0) res[0][23]=a01;
  if (res[0]!=0) res[0][24]=a05;
  if (res[0]!=0) res[0][25]=a01;
  if (res[0]!=0) res[0][26]=a01;
  if (res[0]!=0) res[0][27]=a01;
  if (res[0]!=0) res[0][28]=a06;
  if (res[0]!=0) res[0][29]=a01;
  if (res[0]!=0) res[0][30]=a01;
  a10=cos(a03);
  a10=(a07*a10);
  a10=(a02*a10);
  if (res[0]!=0) res[0][31]=a10;
  if (res[0]!=0) res[0][32]=a01;
  if (res[0]!=0) res[0][33]=a01;
  if (res[0]!=0) res[0][34]=a01;
  if (res[0]!=0) res[0][35]=a08;
  if (res[0]!=0) res[0][36]=a01;
  a07=(a07*a04);
  a07=(a09*a07);
  if (res[0]!=0) res[0][37]=a07;
  if (res[0]!=0) res[0][38]=a01;
  if (res[0]!=0) res[0][39]=a01;
  if (res[0]!=0) res[0][40]=a00;
  if (res[0]!=0) res[0][41]=a01;
  if (res[0]!=0) res[0][42]=a01;
  if (res[0]!=0) res[0][43]=a01;
  if (res[0]!=0) res[0][44]=a05;
  if (res[0]!=0) res[0][45]=a01;
  if (res[0]!=0) res[0][46]=a01;
  if (res[0]!=0) res[0][47]=a01;
  if (res[0]!=0) res[0][48]=a06;
  if (res[0]!=0) res[0][49]=a01;
  a07=9.8100000000000005e+00;
  a04=cos(a03);
  a04=(a07*a04);
  a04=(a02*a04);
  if (res[0]!=0) res[0][50]=a04;
  if (res[0]!=0) res[0][51]=a01;
  if (res[0]!=0) res[0][52]=a01;
  if (res[0]!=0) res[0][53]=a01;
  if (res[0]!=0) res[0][54]=a01;
  if (res[0]!=0) res[0][55]=a08;
  a03=sin(a03);
  a03=(a07*a03);
  a03=(a09*a03);
  if (res[0]!=0) res[0][56]=a03;
  if (res[0]!=0) res[0][57]=a01;
  if (res[0]!=0) res[0][58]=a01;
  if (res[0]!=0) res[0][59]=a01;
  if (res[0]!=0) res[0][60]=a00;
  if (res[0]!=0) res[0][61]=a01;
  if (res[0]!=0) res[0][62]=a01;
  if (res[0]!=0) res[0][63]=a01;
  if (res[0]!=0) res[0][64]=a05;
  if (res[0]!=0) res[0][65]=a01;
  if (res[0]!=0) res[0][66]=a01;
  if (res[0]!=0) res[0][67]=a01;
  if (res[0]!=0) res[0][68]=a06;
  if (res[0]!=0) res[0][69]=a01;
  if (res[0]!=0) res[0][70]=a01;
  if (res[0]!=0) res[0][71]=a01;
  if (res[0]!=0) res[0][72]=a01;
  if (res[0]!=0) res[0][73]=a01;
  if (res[0]!=0) res[0][74]=a01;
  if (res[0]!=0) res[0][75]=a08;
  a08=3.5678400846904044e+00;
  if (res[0]!=0) res[0][76]=a08;
  if (res[0]!=0) res[0][77]=a01;
  if (res[0]!=0) res[0][78]=a01;
  if (res[0]!=0) res[0][79]=a01;
  a06=-7.7525512860840906e-01;
  if (res[0]!=0) res[0][80]=a06;
  if (res[0]!=0) res[0][81]=a01;
  a05=arg[1]? arg[1][13] : 0;
  a00=cos(a05);
  a03=(a02*a00);
  if (res[0]!=0) res[0][82]=a03;
  if (res[0]!=0) res[0][83]=a01;
  a03=-1.0531972647421810e+00;
  if (res[0]!=0) res[0][84]=a03;
  if (res[0]!=0) res[0][85]=a01;
  if (res[0]!=0) res[0][86]=a01;
  if (res[0]!=0) res[0][87]=a01;
  if (res[0]!=0) res[0][88]=a01;
  a04=arg[1]? arg[1][6] : 0;
  a10=sin(a05);
  a10=(a04*a10);
  a10=(a02*a10);
  a10=(-a10);
  if (res[0]!=0) res[0][89]=a10;
  if (res[0]!=0) res[0][90]=a01;
  a10=-1.7393876913398110e+00;
  if (res[0]!=0) res[0][91]=a10;
  if (res[0]!=0) res[0][92]=a01;
  if (res[0]!=0) res[0][93]=a01;
  a00=(a04*a00);
  a00=(a09*a00);
  if (res[0]!=0) res[0][94]=a00;
  if (res[0]!=0) res[0][95]=a01;
  if (res[0]!=0) res[0][96]=a08;
  if (res[0]!=0) res[0][97]=a01;
  if (res[0]!=0) res[0][98]=a01;
  if (res[0]!=0) res[0][99]=a01;
  if (res[0]!=0) res[0][100]=a06;
  a00=sin(a05);
  a11=(a02*a00);
  if (res[0]!=0) res[0][101]=a11;
  if (res[0]!=0) res[0][102]=a01;
  if (res[0]!=0) res[0][103]=a01;
  if (res[0]!=0) res[0][104]=a03;
  if (res[0]!=0) res[0][105]=a01;
  if (res[0]!=0) res[0][106]=a01;
  if (res[0]!=0) res[0][107]=a01;
  a11=cos(a05);
  a11=(a04*a11);
  a11=(a02*a11);
  if (res[0]!=0) res[0][108]=a11;
  if (res[0]!=0) res[0][109]=a01;
  if (res[0]!=0) res[0][110]=a01;
  if (res[0]!=0) res[0][111]=a10;
  if (res[0]!=0) res[0][112]=a01;
  a04=(a04*a00);
  a04=(a09*a04);
  if (res[0]!=0) res[0][113]=a04;
  if (res[0]!=0) res[0][114]=a01;
  if (res[0]!=0) res[0][115]=a01;
  if (res[0]!=0) res[0][116]=a08;
  if (res[0]!=0) res[0][117]=a01;
  if (res[0]!=0) res[0][118]=a01;
  if (res[0]!=0) res[0][119]=a01;
  if (res[0]!=0) res[0][120]=a06;
  if (res[0]!=0) res[0][121]=a01;
  if (res[0]!=0) res[0][122]=a01;
  if (res[0]!=0) res[0][123]=a01;
  if (res[0]!=0) res[0][124]=a03;
  if (res[0]!=0) res[0][125]=a01;
  if (res[0]!=0) res[0][126]=a01;
  a04=cos(a05);
  a04=(a07*a04);
  a04=(a02*a04);
  if (res[0]!=0) res[0][127]=a04;
  if (res[0]!=0) res[0][128]=a01;
  if (res[0]!=0) res[0][129]=a01;
  if (res[0]!=0) res[0][130]=a01;
  if (res[0]!=0) res[0][131]=a10;
  a05=sin(a05);
  a05=(a07*a05);
  a05=(a09*a05);
  if (res[0]!=0) res[0][132]=a05;
  if (res[0]!=0) res[0][133]=a01;
  if (res[0]!=0) res[0][134]=a01;
  if (res[0]!=0) res[0][135]=a01;
  if (res[0]!=0) res[0][136]=a08;
  if (res[0]!=0) res[0][137]=a01;
  if (res[0]!=0) res[0][138]=a01;
  if (res[0]!=0) res[0][139]=a01;
  if (res[0]!=0) res[0][140]=a06;
  if (res[0]!=0) res[0][141]=a01;
  if (res[0]!=0) res[0][142]=a01;
  if (res[0]!=0) res[0][143]=a01;
  if (res[0]!=0) res[0][144]=a03;
  if (res[0]!=0) res[0][145]=a01;
  if (res[0]!=0) res[0][146]=a01;
  if (res[0]!=0) res[0][147]=a01;
  if (res[0]!=0) res[0][148]=a01;
  if (res[0]!=0) res[0][149]=a01;
  if (res[0]!=0) res[0][150]=a01;
  if (res[0]!=0) res[0][151]=a10;
  a10=-5.5319726474218047e+00;
  if (res[0]!=0) res[0][152]=a10;
  if (res[0]!=0) res[0][153]=a01;
  if (res[0]!=0) res[0][154]=a01;
  if (res[0]!=0) res[0][155]=a01;
  a03=7.5319726474218074e+00;
  if (res[0]!=0) res[0][156]=a03;
  if (res[0]!=0) res[0][157]=a01;
  if (res[0]!=0) res[0][158]=a01;
  if (res[0]!=0) res[0][159]=a01;
  a06=-5.;
  if (res[0]!=0) res[0][160]=a06;
  if (res[0]!=0) res[0][161]=a01;
  a08=arg[1]? arg[1][14] : 0;
  a05=cos(a08);
  a04=(a02*a05);
  if (res[0]!=0) res[0][162]=a04;
  if (res[0]!=0) res[0][163]=a01;
  if (res[0]!=0) res[0][164]=a01;
  if (res[0]!=0) res[0][165]=a01;
  a04=arg[1]? arg[1][10] : 0;
  a00=sin(a08);
  a00=(a04*a00);
  a00=(a02*a00);
  a00=(-a00);
  if (res[0]!=0) res[0][166]=a00;
  a00=3.0000000000000018e+00;
  if (res[0]!=0) res[0][167]=a00;
  if (res[0]!=0) res[0][168]=a01;
  if (res[0]!=0) res[0][169]=a01;
  a05=(a04*a05);
  a05=(a09*a05);
  if (res[0]!=0) res[0][170]=a05;
  if (res[0]!=0) res[0][171]=a01;
  if (res[0]!=0) res[0][172]=a10;
  if (res[0]!=0) res[0][173]=a01;
  if (res[0]!=0) res[0][174]=a01;
  if (res[0]!=0) res[0][175]=a01;
  if (res[0]!=0) res[0][176]=a03;
  if (res[0]!=0) res[0][177]=a01;
  if (res[0]!=0) res[0][178]=a01;
  if (res[0]!=0) res[0][179]=a01;
  if (res[0]!=0) res[0][180]=a06;
  a05=sin(a08);
  a11=(a02*a05);
  if (res[0]!=0) res[0][181]=a11;
  if (res[0]!=0) res[0][182]=a01;
  if (res[0]!=0) res[0][183]=a01;
  if (res[0]!=0) res[0][184]=a01;
  a11=cos(a08);
  a11=(a04*a11);
  a11=(a02*a11);
  if (res[0]!=0) res[0][185]=a11;
  if (res[0]!=0) res[0][186]=a01;
  if (res[0]!=0) res[0][187]=a00;
  if (res[0]!=0) res[0][188]=a01;
  a04=(a04*a05);
  a04=(a09*a04);
  if (res[0]!=0) res[0][189]=a04;
  if (res[0]!=0) res[0][190]=a01;
  if (res[0]!=0) res[0][191]=a01;
  if (res[0]!=0) res[0][192]=a10;
  if (res[0]!=0) res[0][193]=a01;
  if (res[0]!=0) res[0][194]=a01;
  if (res[0]!=0) res[0][195]=a01;
  if (res[0]!=0) res[0][196]=a03;
  if (res[0]!=0) res[0][197]=a01;
  if (res[0]!=0) res[0][198]=a01;
  if (res[0]!=0) res[0][199]=a01;
  if (res[0]!=0) res[0][200]=a06;
  if (res[0]!=0) res[0][201]=a01;
  if (res[0]!=0) res[0][202]=a01;
  if (res[0]!=0) res[0][203]=a01;
  a04=cos(a08);
  a04=(a07*a04);
  a02=(a02*a04);
  if (res[0]!=0) res[0][204]=a02;
  if (res[0]!=0) res[0][205]=a01;
  if (res[0]!=0) res[0][206]=a01;
  if (res[0]!=0) res[0][207]=a00;
  a08=sin(a08);
  a07=(a07*a08);
  a09=(a09*a07);
  if (res[0]!=0) res[0][208]=a09;
  if (res[0]!=0) res[0][209]=a01;
  if (res[0]!=0) res[0][210]=a01;
  if (res[0]!=0) res[0][211]=a01;
  if (res[0]!=0) res[0][212]=a10;
  if (res[0]!=0) res[0][213]=a01;
  if (res[0]!=0) res[0][214]=a01;
  if (res[0]!=0) res[0][215]=a01;
  if (res[0]!=0) res[0][216]=a03;
  if (res[0]!=0) res[0][217]=a01;
  if (res[0]!=0) res[0][218]=a01;
  if (res[0]!=0) res[0][219]=a01;
  if (res[0]!=0) res[0][220]=a06;
  if (res[0]!=0) res[0][221]=a01;
  if (res[0]!=0) res[0][222]=a01;
  if (res[0]!=0) res[0][223]=a01;
  if (res[0]!=0) res[0][224]=a01;
  if (res[0]!=0) res[0][225]=a01;
  if (res[0]!=0) res[0][226]=a01;
  if (res[0]!=0) res[0][227]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_incref(void) {
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_J_Ggt_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_J_Ggt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real brach_eval_J_Ggt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_J_Ggt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_J_Ggt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_J_Ggt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_J_Ggt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* brach_eval_J_Ggt_ineq:(i0[4],i1[15])->(o0[19x19]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  a1=1.;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  if (res[0]!=0) res[0][23]=a0;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a0;
  if (res[0]!=0) res[0][27]=a0;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  if (res[0]!=0) res[0][31]=a0;
  if (res[0]!=0) res[0][32]=a0;
  if (res[0]!=0) res[0][33]=a0;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a1;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  if (res[0]!=0) res[0][43]=a0;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a0;
  if (res[0]!=0) res[0][55]=a1;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  if (res[0]!=0) res[0][58]=a0;
  if (res[0]!=0) res[0][59]=a0;
  if (res[0]!=0) res[0][60]=a0;
  if (res[0]!=0) res[0][61]=a0;
  if (res[0]!=0) res[0][62]=a0;
  if (res[0]!=0) res[0][63]=a0;
  if (res[0]!=0) res[0][64]=a0;
  if (res[0]!=0) res[0][65]=a0;
  if (res[0]!=0) res[0][66]=a0;
  if (res[0]!=0) res[0][67]=a0;
  if (res[0]!=0) res[0][68]=a0;
  if (res[0]!=0) res[0][69]=a0;
  if (res[0]!=0) res[0][70]=a0;
  if (res[0]!=0) res[0][71]=a0;
  if (res[0]!=0) res[0][72]=a0;
  if (res[0]!=0) res[0][73]=a0;
  if (res[0]!=0) res[0][74]=a0;
  if (res[0]!=0) res[0][75]=a1;
  if (res[0]!=0) res[0][76]=a1;
  if (res[0]!=0) res[0][77]=a0;
  if (res[0]!=0) res[0][78]=a0;
  if (res[0]!=0) res[0][79]=a0;
  if (res[0]!=0) res[0][80]=a0;
  if (res[0]!=0) res[0][81]=a0;
  if (res[0]!=0) res[0][82]=a0;
  if (res[0]!=0) res[0][83]=a0;
  if (res[0]!=0) res[0][84]=a0;
  if (res[0]!=0) res[0][85]=a0;
  if (res[0]!=0) res[0][86]=a0;
  if (res[0]!=0) res[0][87]=a0;
  if (res[0]!=0) res[0][88]=a0;
  if (res[0]!=0) res[0][89]=a0;
  if (res[0]!=0) res[0][90]=a0;
  if (res[0]!=0) res[0][91]=a0;
  if (res[0]!=0) res[0][92]=a0;
  if (res[0]!=0) res[0][93]=a0;
  if (res[0]!=0) res[0][94]=a0;
  if (res[0]!=0) res[0][95]=a0;
  if (res[0]!=0) res[0][96]=a1;
  if (res[0]!=0) res[0][97]=a0;
  if (res[0]!=0) res[0][98]=a0;
  if (res[0]!=0) res[0][99]=a0;
  if (res[0]!=0) res[0][100]=a0;
  if (res[0]!=0) res[0][101]=a0;
  if (res[0]!=0) res[0][102]=a0;
  if (res[0]!=0) res[0][103]=a0;
  if (res[0]!=0) res[0][104]=a0;
  if (res[0]!=0) res[0][105]=a0;
  if (res[0]!=0) res[0][106]=a0;
  if (res[0]!=0) res[0][107]=a0;
  if (res[0]!=0) res[0][108]=a0;
  if (res[0]!=0) res[0][109]=a0;
  if (res[0]!=0) res[0][110]=a0;
  if (res[0]!=0) res[0][111]=a0;
  if (res[0]!=0) res[0][112]=a0;
  if (res[0]!=0) res[0][113]=a0;
  if (res[0]!=0) res[0][114]=a0;
  if (res[0]!=0) res[0][115]=a0;
  if (res[0]!=0) res[0][116]=a1;
  if (res[0]!=0) res[0][117]=a0;
  if (res[0]!=0) res[0][118]=a0;
  if (res[0]!=0) res[0][119]=a0;
  if (res[0]!=0) res[0][120]=a0;
  if (res[0]!=0) res[0][121]=a0;
  if (res[0]!=0) res[0][122]=a0;
  if (res[0]!=0) res[0][123]=a0;
  if (res[0]!=0) res[0][124]=a0;
  if (res[0]!=0) res[0][125]=a0;
  if (res[0]!=0) res[0][126]=a0;
  if (res[0]!=0) res[0][127]=a0;
  if (res[0]!=0) res[0][128]=a0;
  if (res[0]!=0) res[0][129]=a0;
  if (res[0]!=0) res[0][130]=a0;
  if (res[0]!=0) res[0][131]=a0;
  if (res[0]!=0) res[0][132]=a0;
  if (res[0]!=0) res[0][133]=a0;
  if (res[0]!=0) res[0][134]=a0;
  if (res[0]!=0) res[0][135]=a0;
  if (res[0]!=0) res[0][136]=a1;
  if (res[0]!=0) res[0][137]=a0;
  if (res[0]!=0) res[0][138]=a0;
  if (res[0]!=0) res[0][139]=a0;
  if (res[0]!=0) res[0][140]=a0;
  if (res[0]!=0) res[0][141]=a0;
  if (res[0]!=0) res[0][142]=a0;
  if (res[0]!=0) res[0][143]=a0;
  if (res[0]!=0) res[0][144]=a0;
  if (res[0]!=0) res[0][145]=a0;
  if (res[0]!=0) res[0][146]=a0;
  if (res[0]!=0) res[0][147]=a0;
  if (res[0]!=0) res[0][148]=a0;
  if (res[0]!=0) res[0][149]=a0;
  if (res[0]!=0) res[0][150]=a0;
  if (res[0]!=0) res[0][151]=a0;
  if (res[0]!=0) res[0][152]=a0;
  if (res[0]!=0) res[0][153]=a0;
  if (res[0]!=0) res[0][154]=a0;
  if (res[0]!=0) res[0][155]=a0;
  if (res[0]!=0) res[0][156]=a1;
  if (res[0]!=0) res[0][157]=a0;
  if (res[0]!=0) res[0][158]=a0;
  if (res[0]!=0) res[0][159]=a0;
  if (res[0]!=0) res[0][160]=a0;
  if (res[0]!=0) res[0][161]=a0;
  if (res[0]!=0) res[0][162]=a0;
  if (res[0]!=0) res[0][163]=a0;
  if (res[0]!=0) res[0][164]=a0;
  if (res[0]!=0) res[0][165]=a0;
  if (res[0]!=0) res[0][166]=a0;
  if (res[0]!=0) res[0][167]=a0;
  if (res[0]!=0) res[0][168]=a0;
  if (res[0]!=0) res[0][169]=a0;
  if (res[0]!=0) res[0][170]=a0;
  if (res[0]!=0) res[0][171]=a0;
  if (res[0]!=0) res[0][172]=a0;
  if (res[0]!=0) res[0][173]=a0;
  if (res[0]!=0) res[0][174]=a0;
  if (res[0]!=0) res[0][175]=a0;
  if (res[0]!=0) res[0][176]=a1;
  if (res[0]!=0) res[0][177]=a0;
  if (res[0]!=0) res[0][178]=a0;
  if (res[0]!=0) res[0][179]=a0;
  if (res[0]!=0) res[0][180]=a0;
  if (res[0]!=0) res[0][181]=a0;
  if (res[0]!=0) res[0][182]=a0;
  if (res[0]!=0) res[0][183]=a0;
  if (res[0]!=0) res[0][184]=a0;
  if (res[0]!=0) res[0][185]=a0;
  if (res[0]!=0) res[0][186]=a0;
  if (res[0]!=0) res[0][187]=a0;
  if (res[0]!=0) res[0][188]=a0;
  if (res[0]!=0) res[0][189]=a0;
  if (res[0]!=0) res[0][190]=a0;
  if (res[0]!=0) res[0][191]=a0;
  if (res[0]!=0) res[0][192]=a0;
  if (res[0]!=0) res[0][193]=a0;
  if (res[0]!=0) res[0][194]=a0;
  if (res[0]!=0) res[0][195]=a0;
  if (res[0]!=0) res[0][196]=a1;
  if (res[0]!=0) res[0][197]=a0;
  if (res[0]!=0) res[0][198]=a0;
  if (res[0]!=0) res[0][199]=a0;
  if (res[0]!=0) res[0][200]=a0;
  if (res[0]!=0) res[0][201]=a0;
  if (res[0]!=0) res[0][202]=a0;
  if (res[0]!=0) res[0][203]=a0;
  if (res[0]!=0) res[0][204]=a0;
  if (res[0]!=0) res[0][205]=a0;
  if (res[0]!=0) res[0][206]=a0;
  if (res[0]!=0) res[0][207]=a0;
  if (res[0]!=0) res[0][208]=a0;
  if (res[0]!=0) res[0][209]=a0;
  if (res[0]!=0) res[0][210]=a0;
  if (res[0]!=0) res[0][211]=a0;
  if (res[0]!=0) res[0][212]=a0;
  if (res[0]!=0) res[0][213]=a0;
  if (res[0]!=0) res[0][214]=a0;
  if (res[0]!=0) res[0][215]=a0;
  if (res[0]!=0) res[0][216]=a1;
  if (res[0]!=0) res[0][217]=a0;
  if (res[0]!=0) res[0][218]=a0;
  if (res[0]!=0) res[0][219]=a0;
  if (res[0]!=0) res[0][220]=a0;
  if (res[0]!=0) res[0][221]=a0;
  if (res[0]!=0) res[0][222]=a0;
  if (res[0]!=0) res[0][223]=a0;
  if (res[0]!=0) res[0][224]=a0;
  if (res[0]!=0) res[0][225]=a0;
  if (res[0]!=0) res[0][226]=a0;
  if (res[0]!=0) res[0][227]=a0;
  if (res[0]!=0) res[0][228]=a0;
  if (res[0]!=0) res[0][229]=a0;
  if (res[0]!=0) res[0][230]=a0;
  if (res[0]!=0) res[0][231]=a0;
  if (res[0]!=0) res[0][232]=a0;
  if (res[0]!=0) res[0][233]=a0;
  if (res[0]!=0) res[0][234]=a0;
  if (res[0]!=0) res[0][235]=a0;
  if (res[0]!=0) res[0][236]=a1;
  if (res[0]!=0) res[0][237]=a0;
  if (res[0]!=0) res[0][238]=a0;
  if (res[0]!=0) res[0][239]=a0;
  if (res[0]!=0) res[0][240]=a0;
  if (res[0]!=0) res[0][241]=a0;
  if (res[0]!=0) res[0][242]=a0;
  if (res[0]!=0) res[0][243]=a0;
  if (res[0]!=0) res[0][244]=a0;
  if (res[0]!=0) res[0][245]=a0;
  if (res[0]!=0) res[0][246]=a0;
  if (res[0]!=0) res[0][247]=a0;
  if (res[0]!=0) res[0][248]=a0;
  if (res[0]!=0) res[0][249]=a0;
  if (res[0]!=0) res[0][250]=a0;
  if (res[0]!=0) res[0][251]=a0;
  if (res[0]!=0) res[0][252]=a0;
  if (res[0]!=0) res[0][253]=a0;
  if (res[0]!=0) res[0][254]=a0;
  if (res[0]!=0) res[0][255]=a0;
  if (res[0]!=0) res[0][256]=a1;
  if (res[0]!=0) res[0][257]=a0;
  if (res[0]!=0) res[0][258]=a0;
  if (res[0]!=0) res[0][259]=a0;
  if (res[0]!=0) res[0][260]=a0;
  if (res[0]!=0) res[0][261]=a0;
  if (res[0]!=0) res[0][262]=a0;
  if (res[0]!=0) res[0][263]=a0;
  if (res[0]!=0) res[0][264]=a0;
  if (res[0]!=0) res[0][265]=a0;
  if (res[0]!=0) res[0][266]=a0;
  if (res[0]!=0) res[0][267]=a0;
  if (res[0]!=0) res[0][268]=a0;
  if (res[0]!=0) res[0][269]=a0;
  if (res[0]!=0) res[0][270]=a0;
  if (res[0]!=0) res[0][271]=a0;
  if (res[0]!=0) res[0][272]=a0;
  if (res[0]!=0) res[0][273]=a0;
  if (res[0]!=0) res[0][274]=a0;
  if (res[0]!=0) res[0][275]=a0;
  if (res[0]!=0) res[0][276]=a1;
  if (res[0]!=0) res[0][277]=a0;
  if (res[0]!=0) res[0][278]=a0;
  if (res[0]!=0) res[0][279]=a0;
  if (res[0]!=0) res[0][280]=a0;
  if (res[0]!=0) res[0][281]=a0;
  if (res[0]!=0) res[0][282]=a0;
  if (res[0]!=0) res[0][283]=a0;
  if (res[0]!=0) res[0][284]=a0;
  if (res[0]!=0) res[0][285]=a0;
  if (res[0]!=0) res[0][286]=a0;
  if (res[0]!=0) res[0][287]=a0;
  if (res[0]!=0) res[0][288]=a0;
  if (res[0]!=0) res[0][289]=a0;
  if (res[0]!=0) res[0][290]=a0;
  if (res[0]!=0) res[0][291]=a0;
  if (res[0]!=0) res[0][292]=a0;
  if (res[0]!=0) res[0][293]=a0;
  if (res[0]!=0) res[0][294]=a0;
  if (res[0]!=0) res[0][295]=a0;
  if (res[0]!=0) res[0][296]=a1;
  if (res[0]!=0) res[0][297]=a0;
  if (res[0]!=0) res[0][298]=a0;
  if (res[0]!=0) res[0][299]=a0;
  if (res[0]!=0) res[0][300]=a0;
  if (res[0]!=0) res[0][301]=a0;
  if (res[0]!=0) res[0][302]=a0;
  if (res[0]!=0) res[0][303]=a0;
  if (res[0]!=0) res[0][304]=a0;
  if (res[0]!=0) res[0][305]=a0;
  if (res[0]!=0) res[0][306]=a0;
  if (res[0]!=0) res[0][307]=a0;
  if (res[0]!=0) res[0][308]=a0;
  if (res[0]!=0) res[0][309]=a0;
  if (res[0]!=0) res[0][310]=a0;
  if (res[0]!=0) res[0][311]=a0;
  if (res[0]!=0) res[0][312]=a0;
  if (res[0]!=0) res[0][313]=a0;
  if (res[0]!=0) res[0][314]=a0;
  if (res[0]!=0) res[0][315]=a0;
  if (res[0]!=0) res[0][316]=a1;
  if (res[0]!=0) res[0][317]=a0;
  if (res[0]!=0) res[0][318]=a0;
  if (res[0]!=0) res[0][319]=a0;
  if (res[0]!=0) res[0][320]=a0;
  if (res[0]!=0) res[0][321]=a0;
  if (res[0]!=0) res[0][322]=a0;
  if (res[0]!=0) res[0][323]=a0;
  if (res[0]!=0) res[0][324]=a0;
  if (res[0]!=0) res[0][325]=a0;
  if (res[0]!=0) res[0][326]=a0;
  if (res[0]!=0) res[0][327]=a0;
  if (res[0]!=0) res[0][328]=a0;
  if (res[0]!=0) res[0][329]=a0;
  if (res[0]!=0) res[0][330]=a0;
  if (res[0]!=0) res[0][331]=a0;
  if (res[0]!=0) res[0][332]=a0;
  if (res[0]!=0) res[0][333]=a0;
  if (res[0]!=0) res[0][334]=a0;
  if (res[0]!=0) res[0][335]=a0;
  if (res[0]!=0) res[0][336]=a1;
  if (res[0]!=0) res[0][337]=a0;
  if (res[0]!=0) res[0][338]=a0;
  if (res[0]!=0) res[0][339]=a0;
  if (res[0]!=0) res[0][340]=a0;
  if (res[0]!=0) res[0][341]=a0;
  if (res[0]!=0) res[0][342]=a0;
  if (res[0]!=0) res[0][343]=a0;
  if (res[0]!=0) res[0][344]=a0;
  if (res[0]!=0) res[0][345]=a0;
  if (res[0]!=0) res[0][346]=a0;
  if (res[0]!=0) res[0][347]=a0;
  if (res[0]!=0) res[0][348]=a0;
  if (res[0]!=0) res[0][349]=a0;
  if (res[0]!=0) res[0][350]=a0;
  if (res[0]!=0) res[0][351]=a0;
  if (res[0]!=0) res[0][352]=a0;
  if (res[0]!=0) res[0][353]=a0;
  if (res[0]!=0) res[0][354]=a0;
  if (res[0]!=0) res[0][355]=a0;
  if (res[0]!=0) res[0][356]=a1;
  if (res[0]!=0) res[0][357]=a0;
  if (res[0]!=0) res[0][358]=a0;
  if (res[0]!=0) res[0][359]=a0;
  if (res[0]!=0) res[0][360]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_ineq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_ineq_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_ineq_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_ineq_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_ineq_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_ineq_release(int mem) {
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_ineq_incref(void) {
}

CASADI_SYMBOL_EXPORT void brach_eval_J_Ggt_ineq_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_J_Ggt_ineq_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_J_Ggt_ineq_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real brach_eval_J_Ggt_ineq_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_J_Ggt_ineq_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_J_Ggt_ineq_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_J_Ggt_ineq_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_J_Ggt_ineq_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_ineq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_J_Ggt_ineq_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* brach_eval_H_RSQrqt:(i0[4],i1[15],i2[4],i3[12],i4[19])->(o0[19x19]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  if (res[0]!=0) res[0][3]=a00;
  if (res[0]!=0) res[0][4]=a00;
  if (res[0]!=0) res[0][5]=a00;
  if (res[0]!=0) res[0][6]=a00;
  if (res[0]!=0) res[0][7]=a00;
  if (res[0]!=0) res[0][8]=a00;
  if (res[0]!=0) res[0][9]=a00;
  if (res[0]!=0) res[0][10]=a00;
  if (res[0]!=0) res[0][11]=a00;
  if (res[0]!=0) res[0][12]=a00;
  if (res[0]!=0) res[0][13]=a00;
  if (res[0]!=0) res[0][14]=a00;
  if (res[0]!=0) res[0][15]=a00;
  if (res[0]!=0) res[0][16]=a00;
  if (res[0]!=0) res[0][17]=a00;
  if (res[0]!=0) res[0][18]=a00;
  if (res[0]!=0) res[0][19]=a00;
  if (res[0]!=0) res[0][20]=a00;
  if (res[0]!=0) res[0][21]=a00;
  if (res[0]!=0) res[0][22]=a00;
  if (res[0]!=0) res[0][23]=a00;
  if (res[0]!=0) res[0][24]=a00;
  if (res[0]!=0) res[0][25]=a00;
  if (res[0]!=0) res[0][26]=a00;
  if (res[0]!=0) res[0][27]=a00;
  if (res[0]!=0) res[0][28]=a00;
  if (res[0]!=0) res[0][29]=a00;
  if (res[0]!=0) res[0][30]=a00;
  if (res[0]!=0) res[0][31]=a00;
  if (res[0]!=0) res[0][32]=a00;
  if (res[0]!=0) res[0][33]=a00;
  if (res[0]!=0) res[0][34]=a00;
  if (res[0]!=0) res[0][35]=a00;
  if (res[0]!=0) res[0][36]=a00;
  if (res[0]!=0) res[0][37]=a00;
  if (res[0]!=0) res[0][38]=a00;
  if (res[0]!=0) res[0][39]=a00;
  if (res[0]!=0) res[0][40]=a00;
  if (res[0]!=0) res[0][41]=a00;
  if (res[0]!=0) res[0][42]=a00;
  if (res[0]!=0) res[0][43]=a00;
  if (res[0]!=0) res[0][44]=a00;
  if (res[0]!=0) res[0][45]=a00;
  if (res[0]!=0) res[0][46]=a00;
  if (res[0]!=0) res[0][47]=a00;
  if (res[0]!=0) res[0][48]=a00;
  if (res[0]!=0) res[0][49]=a00;
  a01=arg[1]? arg[1][12] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][3] : 0;
  a04=20.;
  a03=(a03/a04);
  a04=arg[3]? arg[3][1] : 0;
  a05=(a03*a04);
  a06=(a02*a05);
  a07=sin(a01);
  a08=arg[3]? arg[3][0] : 0;
  a09=(a03*a08);
  a10=(a07*a09);
  a06=(a06-a10);
  if (res[0]!=0) res[0][50]=a06;
  if (res[0]!=0) res[0][51]=a00;
  if (res[0]!=0) res[0][52]=a00;
  if (res[0]!=0) res[0][53]=a00;
  if (res[0]!=0) res[0][54]=a00;
  if (res[0]!=0) res[0][55]=a00;
  a10=sin(a01);
  a11=5.0000000000000003e-02;
  a04=(a11*a04);
  a10=(a10*a04);
  a12=cos(a01);
  a08=(a11*a08);
  a12=(a12*a08);
  a10=(a10+a12);
  if (res[0]!=0) res[0][56]=a10;
  if (res[0]!=0) res[0][57]=a00;
  if (res[0]!=0) res[0][58]=a00;
  if (res[0]!=0) res[0][59]=a00;
  if (res[0]!=0) res[0][60]=a00;
  if (res[0]!=0) res[0][61]=a00;
  if (res[0]!=0) res[0][62]=a00;
  if (res[0]!=0) res[0][63]=a00;
  if (res[0]!=0) res[0][64]=a00;
  if (res[0]!=0) res[0][65]=a00;
  if (res[0]!=0) res[0][66]=a00;
  if (res[0]!=0) res[0][67]=a00;
  if (res[0]!=0) res[0][68]=a00;
  if (res[0]!=0) res[0][69]=a00;
  if (res[0]!=0) res[0][70]=a00;
  if (res[0]!=0) res[0][71]=a00;
  if (res[0]!=0) res[0][72]=a00;
  if (res[0]!=0) res[0][73]=a00;
  if (res[0]!=0) res[0][74]=a00;
  if (res[0]!=0) res[0][75]=a00;
  if (res[0]!=0) res[0][76]=a00;
  if (res[0]!=0) res[0][77]=a00;
  if (res[0]!=0) res[0][78]=a00;
  if (res[0]!=0) res[0][79]=a00;
  if (res[0]!=0) res[0][80]=a00;
  if (res[0]!=0) res[0][81]=a00;
  if (res[0]!=0) res[0][82]=a00;
  if (res[0]!=0) res[0][83]=a00;
  if (res[0]!=0) res[0][84]=a00;
  if (res[0]!=0) res[0][85]=a00;
  if (res[0]!=0) res[0][86]=a00;
  if (res[0]!=0) res[0][87]=a00;
  if (res[0]!=0) res[0][88]=a00;
  if (res[0]!=0) res[0][89]=a00;
  if (res[0]!=0) res[0][90]=a00;
  if (res[0]!=0) res[0][91]=a00;
  if (res[0]!=0) res[0][92]=a00;
  if (res[0]!=0) res[0][93]=a00;
  if (res[0]!=0) res[0][94]=a00;
  if (res[0]!=0) res[0][95]=a00;
  if (res[0]!=0) res[0][96]=a00;
  if (res[0]!=0) res[0][97]=a00;
  if (res[0]!=0) res[0][98]=a00;
  if (res[0]!=0) res[0][99]=a00;
  if (res[0]!=0) res[0][100]=a00;
  if (res[0]!=0) res[0][101]=a00;
  if (res[0]!=0) res[0][102]=a00;
  if (res[0]!=0) res[0][103]=a00;
  if (res[0]!=0) res[0][104]=a00;
  if (res[0]!=0) res[0][105]=a00;
  if (res[0]!=0) res[0][106]=a00;
  if (res[0]!=0) res[0][107]=a00;
  if (res[0]!=0) res[0][108]=a00;
  if (res[0]!=0) res[0][109]=a00;
  if (res[0]!=0) res[0][110]=a00;
  if (res[0]!=0) res[0][111]=a00;
  if (res[0]!=0) res[0][112]=a00;
  if (res[0]!=0) res[0][113]=a00;
  if (res[0]!=0) res[0][114]=a00;
  if (res[0]!=0) res[0][115]=a00;
  if (res[0]!=0) res[0][116]=a00;
  if (res[0]!=0) res[0][117]=a00;
  if (res[0]!=0) res[0][118]=a00;
  if (res[0]!=0) res[0][119]=a00;
  if (res[0]!=0) res[0][120]=a00;
  if (res[0]!=0) res[0][121]=a00;
  if (res[0]!=0) res[0][122]=a00;
  if (res[0]!=0) res[0][123]=a00;
  if (res[0]!=0) res[0][124]=a00;
  if (res[0]!=0) res[0][125]=a00;
  if (res[0]!=0) res[0][126]=a00;
  a12=arg[1]? arg[1][13] : 0;
  a13=cos(a12);
  a14=arg[3]? arg[3][5] : 0;
  a15=(a03*a14);
  a16=(a13*a15);
  a17=sin(a12);
  a18=arg[3]? arg[3][4] : 0;
  a19=(a03*a18);
  a20=(a17*a19);
  a16=(a16-a20);
  if (res[0]!=0) res[0][127]=a16;
  if (res[0]!=0) res[0][128]=a00;
  if (res[0]!=0) res[0][129]=a00;
  if (res[0]!=0) res[0][130]=a00;
  if (res[0]!=0) res[0][131]=a00;
  a20=sin(a12);
  a14=(a11*a14);
  a20=(a20*a14);
  a21=cos(a12);
  a18=(a11*a18);
  a21=(a21*a18);
  a20=(a20+a21);
  if (res[0]!=0) res[0][132]=a20;
  if (res[0]!=0) res[0][133]=a00;
  if (res[0]!=0) res[0][134]=a00;
  if (res[0]!=0) res[0][135]=a00;
  if (res[0]!=0) res[0][136]=a00;
  if (res[0]!=0) res[0][137]=a00;
  if (res[0]!=0) res[0][138]=a00;
  if (res[0]!=0) res[0][139]=a00;
  if (res[0]!=0) res[0][140]=a00;
  if (res[0]!=0) res[0][141]=a00;
  if (res[0]!=0) res[0][142]=a00;
  if (res[0]!=0) res[0][143]=a00;
  if (res[0]!=0) res[0][144]=a00;
  if (res[0]!=0) res[0][145]=a00;
  if (res[0]!=0) res[0][146]=a00;
  if (res[0]!=0) res[0][147]=a00;
  if (res[0]!=0) res[0][148]=a00;
  if (res[0]!=0) res[0][149]=a00;
  if (res[0]!=0) res[0][150]=a00;
  if (res[0]!=0) res[0][151]=a00;
  if (res[0]!=0) res[0][152]=a00;
  if (res[0]!=0) res[0][153]=a00;
  if (res[0]!=0) res[0][154]=a00;
  if (res[0]!=0) res[0][155]=a00;
  if (res[0]!=0) res[0][156]=a00;
  if (res[0]!=0) res[0][157]=a00;
  if (res[0]!=0) res[0][158]=a00;
  if (res[0]!=0) res[0][159]=a00;
  if (res[0]!=0) res[0][160]=a00;
  if (res[0]!=0) res[0][161]=a00;
  if (res[0]!=0) res[0][162]=a00;
  if (res[0]!=0) res[0][163]=a00;
  if (res[0]!=0) res[0][164]=a00;
  if (res[0]!=0) res[0][165]=a00;
  if (res[0]!=0) res[0][166]=a00;
  if (res[0]!=0) res[0][167]=a00;
  if (res[0]!=0) res[0][168]=a00;
  if (res[0]!=0) res[0][169]=a00;
  if (res[0]!=0) res[0][170]=a00;
  if (res[0]!=0) res[0][171]=a00;
  if (res[0]!=0) res[0][172]=a00;
  if (res[0]!=0) res[0][173]=a00;
  if (res[0]!=0) res[0][174]=a00;
  if (res[0]!=0) res[0][175]=a00;
  if (res[0]!=0) res[0][176]=a00;
  if (res[0]!=0) res[0][177]=a00;
  if (res[0]!=0) res[0][178]=a00;
  if (res[0]!=0) res[0][179]=a00;
  if (res[0]!=0) res[0][180]=a00;
  if (res[0]!=0) res[0][181]=a00;
  if (res[0]!=0) res[0][182]=a00;
  if (res[0]!=0) res[0][183]=a00;
  if (res[0]!=0) res[0][184]=a00;
  if (res[0]!=0) res[0][185]=a00;
  if (res[0]!=0) res[0][186]=a00;
  if (res[0]!=0) res[0][187]=a00;
  if (res[0]!=0) res[0][188]=a00;
  if (res[0]!=0) res[0][189]=a00;
  if (res[0]!=0) res[0][190]=a00;
  if (res[0]!=0) res[0][191]=a00;
  if (res[0]!=0) res[0][192]=a00;
  if (res[0]!=0) res[0][193]=a00;
  if (res[0]!=0) res[0][194]=a00;
  if (res[0]!=0) res[0][195]=a00;
  if (res[0]!=0) res[0][196]=a00;
  if (res[0]!=0) res[0][197]=a00;
  if (res[0]!=0) res[0][198]=a00;
  if (res[0]!=0) res[0][199]=a00;
  if (res[0]!=0) res[0][200]=a00;
  if (res[0]!=0) res[0][201]=a00;
  if (res[0]!=0) res[0][202]=a00;
  if (res[0]!=0) res[0][203]=a00;
  a21=arg[1]? arg[1][14] : 0;
  a22=cos(a21);
  a23=arg[3]? arg[3][9] : 0;
  a24=(a03*a23);
  a25=(a22*a24);
  a26=sin(a21);
  a27=arg[3]? arg[3][8] : 0;
  a28=(a03*a27);
  a29=(a26*a28);
  a25=(a25-a29);
  if (res[0]!=0) res[0][204]=a25;
  if (res[0]!=0) res[0][205]=a00;
  if (res[0]!=0) res[0][206]=a00;
  if (res[0]!=0) res[0][207]=a00;
  a29=sin(a21);
  a23=(a11*a23);
  a29=(a29*a23);
  a30=cos(a21);
  a27=(a11*a27);
  a30=(a30*a27);
  a29=(a29+a30);
  if (res[0]!=0) res[0][208]=a29;
  if (res[0]!=0) res[0][209]=a00;
  if (res[0]!=0) res[0][210]=a00;
  if (res[0]!=0) res[0][211]=a00;
  if (res[0]!=0) res[0][212]=a00;
  if (res[0]!=0) res[0][213]=a00;
  if (res[0]!=0) res[0][214]=a00;
  if (res[0]!=0) res[0][215]=a00;
  if (res[0]!=0) res[0][216]=a00;
  if (res[0]!=0) res[0][217]=a00;
  if (res[0]!=0) res[0][218]=a00;
  if (res[0]!=0) res[0][219]=a00;
  if (res[0]!=0) res[0][220]=a00;
  if (res[0]!=0) res[0][221]=a00;
  if (res[0]!=0) res[0][222]=a00;
  if (res[0]!=0) res[0][223]=a00;
  if (res[0]!=0) res[0][224]=a00;
  if (res[0]!=0) res[0][225]=a00;
  if (res[0]!=0) res[0][226]=a00;
  if (res[0]!=0) res[0][227]=a00;
  if (res[0]!=0) res[0][228]=a00;
  if (res[0]!=0) res[0][229]=a00;
  if (res[0]!=0) res[0][230]=a06;
  if (res[0]!=0) res[0][231]=a00;
  if (res[0]!=0) res[0][232]=a00;
  if (res[0]!=0) res[0][233]=a00;
  if (res[0]!=0) res[0][234]=a00;
  if (res[0]!=0) res[0][235]=a00;
  if (res[0]!=0) res[0][236]=a00;
  if (res[0]!=0) res[0][237]=a00;
  if (res[0]!=0) res[0][238]=a00;
  if (res[0]!=0) res[0][239]=a00;
  a06=9.8100000000000005e+00;
  a30=arg[3]? arg[3][2] : 0;
  a31=(a03*a30);
  a31=(a06*a31);
  a32=sin(a01);
  a31=(a31*a32);
  a32=arg[1]? arg[1][2] : 0;
  a05=(a32*a05);
  a33=sin(a01);
  a05=(a05*a33);
  a31=(a31+a05);
  a09=(a32*a09);
  a05=cos(a01);
  a09=(a09*a05);
  a31=(a31+a09);
  a31=(-a31);
  if (res[0]!=0) res[0][240]=a31;
  if (res[0]!=0) res[0][241]=a00;
  if (res[0]!=0) res[0][242]=a00;
  if (res[0]!=0) res[0][243]=a00;
  if (res[0]!=0) res[0][244]=a00;
  if (res[0]!=0) res[0][245]=a00;
  a01=cos(a01);
  a30=(a11*a30);
  a30=(a06*a30);
  a01=(a01*a30);
  a04=(a32*a04);
  a02=(a02*a04);
  a01=(a01+a02);
  a32=(a32*a08);
  a07=(a07*a32);
  a01=(a01-a07);
  if (res[0]!=0) res[0][246]=a01;
  if (res[0]!=0) res[0][247]=a00;
  if (res[0]!=0) res[0][248]=a00;
  if (res[0]!=0) res[0][249]=a00;
  if (res[0]!=0) res[0][250]=a00;
  if (res[0]!=0) res[0][251]=a00;
  if (res[0]!=0) res[0][252]=a00;
  if (res[0]!=0) res[0][253]=a16;
  if (res[0]!=0) res[0][254]=a00;
  if (res[0]!=0) res[0][255]=a00;
  if (res[0]!=0) res[0][256]=a00;
  if (res[0]!=0) res[0][257]=a00;
  if (res[0]!=0) res[0][258]=a00;
  if (res[0]!=0) res[0][259]=a00;
  a16=arg[3]? arg[3][6] : 0;
  a07=(a03*a16);
  a07=(a06*a07);
  a32=sin(a12);
  a07=(a07*a32);
  a32=arg[1]? arg[1][6] : 0;
  a15=(a32*a15);
  a08=sin(a12);
  a15=(a15*a08);
  a07=(a07+a15);
  a19=(a32*a19);
  a15=cos(a12);
  a19=(a19*a15);
  a07=(a07+a19);
  a07=(-a07);
  if (res[0]!=0) res[0][260]=a07;
  if (res[0]!=0) res[0][261]=a00;
  if (res[0]!=0) res[0][262]=a00;
  if (res[0]!=0) res[0][263]=a00;
  if (res[0]!=0) res[0][264]=a00;
  a12=cos(a12);
  a16=(a11*a16);
  a16=(a06*a16);
  a12=(a12*a16);
  a14=(a32*a14);
  a13=(a13*a14);
  a12=(a12+a13);
  a32=(a32*a18);
  a17=(a17*a32);
  a12=(a12-a17);
  if (res[0]!=0) res[0][265]=a12;
  if (res[0]!=0) res[0][266]=a00;
  if (res[0]!=0) res[0][267]=a00;
  if (res[0]!=0) res[0][268]=a00;
  if (res[0]!=0) res[0][269]=a00;
  if (res[0]!=0) res[0][270]=a00;
  if (res[0]!=0) res[0][271]=a00;
  if (res[0]!=0) res[0][272]=a00;
  if (res[0]!=0) res[0][273]=a00;
  if (res[0]!=0) res[0][274]=a00;
  if (res[0]!=0) res[0][275]=a00;
  if (res[0]!=0) res[0][276]=a25;
  if (res[0]!=0) res[0][277]=a00;
  if (res[0]!=0) res[0][278]=a00;
  if (res[0]!=0) res[0][279]=a00;
  a25=arg[3]? arg[3][10] : 0;
  a03=(a03*a25);
  a03=(a06*a03);
  a17=sin(a21);
  a03=(a03*a17);
  a17=arg[1]? arg[1][10] : 0;
  a24=(a17*a24);
  a32=sin(a21);
  a24=(a24*a32);
  a03=(a03+a24);
  a28=(a17*a28);
  a24=cos(a21);
  a28=(a28*a24);
  a03=(a03+a28);
  a03=(-a03);
  if (res[0]!=0) res[0][280]=a03;
  if (res[0]!=0) res[0][281]=a00;
  if (res[0]!=0) res[0][282]=a00;
  if (res[0]!=0) res[0][283]=a00;
  a21=cos(a21);
  a11=(a11*a25);
  a06=(a06*a11);
  a21=(a21*a06);
  a23=(a17*a23);
  a22=(a22*a23);
  a21=(a21+a22);
  a17=(a17*a27);
  a26=(a26*a17);
  a21=(a21-a26);
  if (res[0]!=0) res[0][284]=a21;
  if (res[0]!=0) res[0][285]=a00;
  if (res[0]!=0) res[0][286]=a00;
  if (res[0]!=0) res[0][287]=a00;
  if (res[0]!=0) res[0][288]=a00;
  if (res[0]!=0) res[0][289]=a00;
  if (res[0]!=0) res[0][290]=a00;
  if (res[0]!=0) res[0][291]=a00;
  if (res[0]!=0) res[0][292]=a00;
  if (res[0]!=0) res[0][293]=a00;
  if (res[0]!=0) res[0][294]=a00;
  if (res[0]!=0) res[0][295]=a00;
  if (res[0]!=0) res[0][296]=a00;
  if (res[0]!=0) res[0][297]=a00;
  if (res[0]!=0) res[0][298]=a00;
  if (res[0]!=0) res[0][299]=a00;
  if (res[0]!=0) res[0][300]=a00;
  if (res[0]!=0) res[0][301]=a00;
  if (res[0]!=0) res[0][302]=a00;
  if (res[0]!=0) res[0][303]=a00;
  if (res[0]!=0) res[0][304]=a00;
  if (res[0]!=0) res[0][305]=a00;
  if (res[0]!=0) res[0][306]=a00;
  if (res[0]!=0) res[0][307]=a00;
  if (res[0]!=0) res[0][308]=a00;
  if (res[0]!=0) res[0][309]=a00;
  if (res[0]!=0) res[0][310]=a00;
  if (res[0]!=0) res[0][311]=a00;
  if (res[0]!=0) res[0][312]=a00;
  if (res[0]!=0) res[0][313]=a00;
  if (res[0]!=0) res[0][314]=a00;
  if (res[0]!=0) res[0][315]=a00;
  if (res[0]!=0) res[0][316]=a00;
  if (res[0]!=0) res[0][317]=a00;
  if (res[0]!=0) res[0][318]=a00;
  if (res[0]!=0) res[0][319]=a00;
  if (res[0]!=0) res[0][320]=a00;
  if (res[0]!=0) res[0][321]=a00;
  if (res[0]!=0) res[0][322]=a00;
  if (res[0]!=0) res[0][323]=a00;
  if (res[0]!=0) res[0][324]=a00;
  if (res[0]!=0) res[0][325]=a00;
  if (res[0]!=0) res[0][326]=a00;
  if (res[0]!=0) res[0][327]=a00;
  if (res[0]!=0) res[0][328]=a00;
  if (res[0]!=0) res[0][329]=a00;
  if (res[0]!=0) res[0][330]=a00;
  if (res[0]!=0) res[0][331]=a00;
  if (res[0]!=0) res[0][332]=a00;
  if (res[0]!=0) res[0][333]=a00;
  if (res[0]!=0) res[0][334]=a00;
  if (res[0]!=0) res[0][335]=a00;
  if (res[0]!=0) res[0][336]=a00;
  if (res[0]!=0) res[0][337]=a00;
  if (res[0]!=0) res[0][338]=a00;
  if (res[0]!=0) res[0][339]=a00;
  if (res[0]!=0) res[0][340]=a00;
  if (res[0]!=0) res[0][341]=a00;
  if (res[0]!=0) res[0][342]=a00;
  if (res[0]!=0) res[0][343]=a00;
  if (res[0]!=0) res[0][344]=a10;
  if (res[0]!=0) res[0][345]=a00;
  if (res[0]!=0) res[0][346]=a00;
  if (res[0]!=0) res[0][347]=a00;
  if (res[0]!=0) res[0][348]=a20;
  if (res[0]!=0) res[0][349]=a00;
  if (res[0]!=0) res[0][350]=a00;
  if (res[0]!=0) res[0][351]=a00;
  if (res[0]!=0) res[0][352]=a29;
  if (res[0]!=0) res[0][353]=a00;
  if (res[0]!=0) res[0][354]=a01;
  if (res[0]!=0) res[0][355]=a12;
  if (res[0]!=0) res[0][356]=a21;
  if (res[0]!=0) res[0][357]=a00;
  if (res[0]!=0) res[0][358]=a00;
  if (res[0]!=0) res[0][359]=a00;
  if (res[0]!=0) res[0][360]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_H_RSQrqt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int brach_eval_H_RSQrqt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_H_RSQrqt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_H_RSQrqt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int brach_eval_H_RSQrqt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void brach_eval_H_RSQrqt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void brach_eval_H_RSQrqt_incref(void) {
}

CASADI_SYMBOL_EXPORT void brach_eval_H_RSQrqt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_H_RSQrqt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int brach_eval_H_RSQrqt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real brach_eval_H_RSQrqt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_H_RSQrqt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* brach_eval_H_RSQrqt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_H_RSQrqt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* brach_eval_H_RSQrqt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int brach_eval_H_RSQrqt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int brach_eval_H_RSQrqt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
